# Generated by Django 4.1.8 on 2023-06-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LEGO', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setbricks',
            name='type',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
