# Generated by Django 4.1.8 on 2023-06-12 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LEGO', '0002_setbricks_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brick',
            name='avg_price',
        ),
        migrations.RemoveField(
            model_name='brick',
            name='brick_number',
        ),
        migrations.RemoveField(
            model_name='brick',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='brick',
            name='color_id',
        ),
        migrations.RemoveField(
            model_name='brick',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='brick',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='brick',
            name='min_price',
        ),
        migrations.RemoveField(
            model_name='brick',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='brick',
            name='type',
        ),
        migrations.RemoveField(
            model_name='set',
            name='avg_price',
        ),
        migrations.RemoveField(
            model_name='set',
            name='brickprice',
        ),
        migrations.RemoveField(
            model_name='set',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='set',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='set',
            name='min_price',
        ),
        migrations.RemoveField(
            model_name='set',
            name='set_number',
        ),
        migrations.RemoveField(
            model_name='setbricks',
            name='brick_number',
        ),
        migrations.RemoveField(
            model_name='setbricks',
            name='color',
        ),
        migrations.RemoveField(
            model_name='setbricks',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='setbricks',
            name='set_number',
        ),
        migrations.RemoveField(
            model_name='setbricks',
            name='type',
        ),
    ]
