# Generated by Django 4.1.8 on 2023-06-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LEGO', '0004_brick_avg_price_brick_brick_number_brick_category_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='id',
        ),
        migrations.AlterField(
            model_name='set',
            name='set_number',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
