# Generated by Django 4.1.8 on 2023-06-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LEGO', '0005_remove_set_id_alter_set_set_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setbricks',
            name='set_number',
            field=models.CharField(max_length=100),
        ),
    ]
